config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, :set_user, only: [:edit, :update]
  protect_from_forgery except: :update

  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group =Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new, notice: "グループの作成に失敗しました"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, {:user_ids => []})
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def set_user
    @users = Group.find(params[:id]).users
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to action: 'index' }
        format.json
      end
      flash[:notice]= 'メッセージが送信されました'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users=User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message

  %input{name: "utf8", type: "hidden", value: "✓"}/
  %input{name: "authenticity_token", type: "hidden", value: "AxFKlYEhD6eqX1PiZoTYQDANtKvgcFSXZQXHt5hyTl55/U/CHC5rtPavrcu2za65riz4tekZEy56vP6kEb2wYA=="}/
  
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_name"}
        グループ名
    .chat-group-form__field--right
      = f.text_field :name, class: "chat__group_name chat-group-form__input", id: 'chat_group_name.chat-group-form__input', placeholder: 'グループ名を入力してください'
        
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"}
        チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input{class: 'chat-group-form__input', id: 'user-search-field', placeholder: '追加したいユーザー名を入力してください', type: 'text'}
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"}
        チャットメンバー
    .chat-group-form__field--right
      .chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member{id: @user_id}
          %input{name: 'group[user_ids][]', type: "hidden", value: current_user.id, id: "group_user_ids"}
          .chat-group-user__name          
            = current_user.name
      - if @users.present?
        - @users.where.not(id: current_user.id).each do |user|
          .chat-group-user.clearfix.js-chat-member{id: @user_id}
            %input{name: 'group[user_ids][]', type: "hidden", value: user.id, id: "group_user_ids"}
            .chat-group-user__name          
              %li= user.name
            .chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn{data: {user: {id: user.id}}, data: {user: {name: user.name}}}
              削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit '更新する', class: 'chat-group-form__action-btn', "data-disable-with":"Save", name: "commit",id: "group_update"

app/views/groups/_group.html.haml
.side-bar__group
  - current_user.groups.each do |group|
    =link_to group_messages_path(group) do
      %p.side-bar__group__name
        =group.name
      %p.side-bar__group__last-message
        =group.show_last_message

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.side-bar
  .side-bar__user
    %p.side-bar__user__name
      =current_user.name
    .side-bar__user__icon
      =link_to new_group_path do 
        =fa_icon "edit", class: "side-bar__user__icon__edit"
      =link_to edit_user_path(current_user) do
        =fa_icon "cog", class: "side-bar__user__icon__cog"
  =render partial: "messages/group"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  =render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', data: {turbolinks: {track: true}}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/index.html.haml
.side-bar
  .side-bar__user
    %p.side-bar__user__name
      =current_user.name
    .side-bar__user__icon
      =link_to new_group_path do 
        =fa_icon "edit", class: "side-bar__user__icon__edit"
      =link_to edit_user_path(current_user) do
        =fa_icon "cog", class: "side-bar__user__icon__cog"
    =render partial: "messages/group"

.chat
  =link_to "edit", class: "chat__edit-button" do
    Edit
  %p.chat__group
    =@group.name
  %p.chat__member
    group member
  .chat__messages
    =render @messages
  .chat__messages__bottom

  .chat__send
    .chat__send__input-box
      =form_for [@group, @message], html: {id: "new_message"} do |f|
        = f.text_field :content, class: 'chat__send__input-box__text', placeholder: 'type a message'
        = f.label :image, class: 'chat__send__input-box__photo' do
          = fa_icon 'picture-o', class: 'chat__send__input-box__photo__icon'
          = f.file_field :image, class: 'chat__send__input-box__photo__choose'
        = f.submit 'Send', class: 'chat__send__input-box__send-button'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'